version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=524288000
    networks:
      - internal

  drupal:
    build: .
    container_name: ${PROJECT_NAME}-drupal
    depends_on:
      - mysql
      - memcached
    restart: unless-stopped
    volumes:
      - ./docroot:/var/www/html
      - ./config:/home/config
    networks:
      - internal

  webserver:
    image: nginx:1.17.4-alpine
    container_name: ${PROJECT_NAME}-webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docroot:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - internal
      - my-passwords

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT_NAME}-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - internal

  memcached:
    image: memcached:latest
    container_name: ${PROJECT_NAME}-memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    networks:
      - internal

#  certbot:
#    image: certbot/certbot
#    container_name: ${PROJECT_NAME}-certbot
#    depends_on:
#      - webserver
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#      - ./docroot:/var/www/html
#    command: certonly --webroot --webroot-path=/var/www/html --email achraf.jday@gmail.com --agree-tos --no-eff-email --force-renewal -d passwordlocker.me -d www.passwordlocker.me

networks:
  internal:
    driver: bridge
  my-passwords:
    external: true
    name: my-passwords_default

volumes:
  db-data:
  certbot-etc:
